on:
    schedule:
      - cron: "5 * * * *" # a cada 15 minutos  
jobs:
    update-request:
      runs-on: ubuntu-latest
      steps:
        - name: Update Database
          env: 
            SERVER_URL: ${{ secrets.SERVER_URL }}
          run: curl -X GET "$SERVER_URL/update"
  